"""
ovnctl pcap -- port of ovn-pcap.sh

Captures traffic from VM logical ports using OVS port mirroring (SPAN).

For each target VM:
  1. a dedicated internal capture port is created on br-int
     (<mirror_prefix>-<vm>) -- its name never changes, unlike the VM's tap
  2. an OVS mirror copies the VM tap's ingress AND egress into it
  3. tcpdump writes rotated pcaps

The capture survives a VM restart: only the mirror's source port needs
re-pointing (--restart), while the tcpdump process and its output files
stay put.

LAYOUT. Two directories under the one configured path:

    <directory>/inflight/[<vm>/]    tcpdump's open, still-growing file
    <directory>/completed/[<vm>/]   closed files, nothing else

On rotation the hook moves the closed file across. Both sit on the same
filesystem, so that move is a plain rename -- atomic, with no window in
which a partial file is visible under its final name. Whatever collects
the captures takes everything in completed/ and never has to work out
which file tcpdump still has open.

No compression, and no chown anywhere. Access is granted by POSIX ACL to
the account tcpdump drops to (-Z); ownership and mode are left exactly as
the provisioning left them.
"""

from __future__ import annotations

import argparse
import os
import pwd
import re
import shutil
import signal
import subprocess
import time
from pathlib import Path

from .. import libvirtutil, ovn
from ..context import Abort, Ctx
from ..inventory import VM, Inventory
from ..steps import add_step_args

NAME = "pcap"
HELP = "packet capture via OVS port mirroring"

RUNDIR = Path("/run/ovn-pcap")

REQUIRED_CFG = (
    "pcap:directory", "pcap:enabled", "pcap:max_files",
    "pcap:min_free_mb", "pcap:mirror_prefix", "pcap:naming",
    "pcap:rotate_seconds", "pcap:snaplen", "pcap:subdirs", "pcap:targets",
    "topology:br_int",
)

# Generated per --start. -z passes exactly one argument and gives us nowhere
# to put configuration, so the destination and the retention limit are
# baked into the hook.
ROTATE_HOOK = r"""#!/bin/sh
# Generated by ovnctl pcap. Do not edit -- rewritten on every --start.
set -u
DEST="{dest}"
KEEP="{keep}"
POST="{post}"
KEEPORIG="{keep_original}"
PATTERN="{pattern}"

f="${{1:-}}"
[ -n "${{f}}" ] && [ -f "${{f}}" ] || exit 0

# Post-processing, on the closed file, BEFORE it moves. Anything that
# lands in completed/ is finished in every sense.
#
# NOTE ON EVIDENCE: this DELETES packets. If keep_original is true the
# untouched capture is preserved alongside as *.orig.pcap, and that is the
# default -- a filtered capture cannot be un-filtered, and there is no
# record inside it of what was removed.
case "${{POST}}" in
    dedupe)
        [ "${{KEEPORIG}}" = "true" ] && cp -p "${{f}}" "${{f%.pcap}}.orig.pcap"
        if editcap -d "${{f}}" "${{f}}.pp" 2>/dev/null; then
            mv -f "${{f}}.pp" "${{f}}"
        else
            rm -f "${{f}}.pp"
            echo "editcap -d failed on $(basename "${{f}}")" >> "${{DEST}}/.postprocess-failed.log"
        fi
        ;;
    no-retrans)
        [ "${{KEEPORIG}}" = "true" ] && cp -p "${{f}}" "${{f%.pcap}}.orig.pcap"
        if tshark -2 -r "${{f}}" -w "${{f}}.pp" \
             -Y "not tcp.analysis.retransmission and not tcp.analysis.fast_retransmission and not tcp.analysis.spurious_retransmission" 2>/dev/null; then
            mv -f "${{f}}.pp" "${{f}}"
        else
            rm -f "${{f}}.pp"
            echo "tshark filter failed on $(basename "${{f}}")" >> "${{DEST}}/.postprocess-failed.log"
        fi
        ;;
esac

# The move. inflight/ and completed/ are both under the configured
# directory and therefore on one filesystem, so this is a rename: the file
# appears under its final name complete, or not at all. That is the whole
# reason for the two directories -- a collector watching completed/ needs
# no CLOSE_WRITE hook, no lsof, and no rule about skipping the newest file.
#
# A cross-filesystem mv would be a copy-then-unlink and would reintroduce
# exactly the half-written-file window this avoids. If DEST is ever moved
# to another mount, the two-step (.inflight name, then rename) has to come
# back with it.
mv -f "${{f}}" "${{DEST}}/" || exit 1

# The preserved original, if post-processing kept one.
for o in "${{f%.pcap}}".orig.pcap; do
    [ -f "${{o}}" ] && mv -f "${{o}}" "${{DEST}}/"
done

# Retention on completed/, if enabled. 0 keeps everything, which is the
# default: these are engagement captures and silently deleting evidence is
# worse than filling a disk you are already monitoring.
if [ "${{KEEP}}" -gt 0 ] 2>/dev/null; then
    ls -1t ${{DEST}}/${{PATTERN}} 2>/dev/null | tail -n +$((KEEP + 1)) | \
        while IFS= read -r old; do rm -f "${{old}}"; done
fi
exit 0
"""


def register(subparsers) -> argparse.ArgumentParser:
    p = subparsers.add_parser(NAME, help=HELP, description=__doc__,
                              formatter_class=argparse.RawDescriptionHelpFormatter)
    g = p.add_mutually_exclusive_group()
    g.add_argument("--start", action="store_true", help="begin capturing")
    g.add_argument("--stop", action="store_true",
                   help="stop and remove mirrors")
    g.add_argument("--restart", action="store_true",
                   help="re-resolve taps and restart")
    g.add_argument("--status", action="store_true",
                   help="what is running, file sizes, disk free (default)")
    add_step_args(p)
    p.set_defaults(func=main)
    return p


def fs_safe(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]", "_", text)


def safe_name(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", text)


class Pcap:
    def __init__(self, ctx: Ctx):
        self.ctx = ctx
        c = ctx.config

        self.enabled = c.cfg_bool("pcap", "enabled", False)
        self.directory = c.cfg("pcap", "directory")

        # Two subdirectories of it, not two configured paths. Deriving them
        # is what guarantees they share a filesystem, which is what makes
        # the rotation move an atomic rename. A configurable second path
        # could be pointed at another mount and would silently go back to
        # copy-then-unlink.
        self.inflight_name = c.cfg_opt("pcap", "inflight_dir", "inflight")
        self.completed_name = c.cfg_opt("pcap", "completed_dir", "completed")
        self.inflight_root = Path(self.directory) / self.inflight_name
        self.completed_root = Path(self.directory) / self.completed_name

        self.archive_max = c.cfg_opt("pcap", "archive_max_files", "0")
        self.archive_reader = c.cfg_opt("pcap", "archive_reader", "")
        self.post = c.cfg_opt("pcap", "post_process", "none")
        self.keep_original = c.cfg_opt("pcap", "keep_original", "true")

        self.targets = c.cfg("pcap", "targets")
        self.snaplen = c.cfg("pcap", "snaplen")
        self.filter = c.cfg_opt("pcap", "filter", "")
        self.rotate = c.cfg("pcap", "rotate_seconds")
        self.max_files = c.cfg("pcap", "max_files")
        self.prefix = c.cfg("pcap", "mirror_prefix")
        self.drop_user_cfg = c.cfg_opt("pcap", "drop_user", "tcpdump")
        self.min_free_mb = c.cfg_int("pcap", "min_free_mb")
        self.subdirs = c.cfg_bool("pcap", "subdirs", True)
        self.file_prefix = c.cfg_opt("pcap", "file_prefix", "internal")
        self.naming = c.cfg("pcap", "naming")   # auto | inventory | libvirt

        self.br_int = c.cfg("topology", "br_int")

        self.inv = Inventory(c)
        self.vms = self._load_targets()

        self.have_virsh = libvirtutil.available(ctx)
        self.mac_tap: dict[str, str] = {}
        self.mac_domain: dict[str, str] = {}
        self.name_override = self._load_name_map()
        self.drop_user = "root"

    # ------------------------------------------------------------------
    def _load_targets(self) -> list[VM]:
        vms = self.inv.select(self.targets)
        if not vms:
            raise Abort(f"No VMs matched pcap.targets='{self.targets}'.")
        return vms

    def _load_name_map(self) -> dict[str, str]:
        """Explicit inventory-name -> libvirt-domain overrides from [vm_names]."""
        out: dict[str, str] = {}
        for entry in self.ctx.cfg_list("vm_names", "map"):
            parts = entry.split()
            if len(parts) >= 2:
                out[parts[0]] = parts[1]
        return out

    def build_virsh_map(self) -> None:
        if self.have_virsh:
            self.mac_tap, self.mac_domain = libvirtutil.mac_maps(self.ctx)

    # ------------------------------------------------------------------
    def tap_for(self, vm: VM) -> str:
        """The local tap carrying this logical port.

        Resolved from OVS, not libvirt: ovn-controller binds a port by
        matching external-ids:iface-id on a local interface, so OVS holds
        the definitive mapping -- and it works on a host with no libvirt
        CLI, which is what previously made every VM look "not running" and
        get silently skipped.
        """
        ctx = self.ctx
        tap = ovn.iface_for_iface_id(ctx, vm.uuid)
        if tap:
            return tap
        tap = ctx.qout("ovs-vsctl", "--bare", "--columns=name", "find",
                       "Interface", f"external-ids:attached-mac={vm.mac_lc}")
        if tap.strip():
            return tap.splitlines()[0].strip()
        # libvirt is only a fallback now, for a tap with no iface-id set.
        return self.mac_tap.get(vm.mac_lc, "")

    def tap_absent_reason(self, vm: VM) -> str:
        """Explain a missing tap instead of asserting the VM is off."""
        if ovn.port_binding_chassis(self.ctx, vm.uuid):
            return "bound to a chassis, but no local interface carries its iface-id"
        return "logical port not bound -- VM powered off, or its tap is not on br-int"

    def label_for(self, vm: VM) -> str:
        """The human-facing name used for directories and filenames.

        Explicit map wins, then the live libvirt domain, then the inventory
        name.
        """
        if self.naming == "inventory":
            return fs_safe(vm.name)
        if self.naming == "libvirt":
            label = self.name_override.get(vm.name) or self.mac_domain.get(vm.mac_lc)
            if not label:
                self.ctx.warn(f"No libvirt domain known for {vm.name} "
                              "(not running, and no [vm_names].map entry).")
                self.ctx.warn("  Falling back to the inventory name for its "
                              "capture path.")
                label = vm.name
            return fs_safe(label)
        label = (self.name_override.get(vm.name)
                 or self.mac_domain.get(vm.mac_lc)
                 or vm.name)
        return fs_safe(label)

    # ------------------------------------------------------------------
    def vm_dir(self, label: str) -> Path:
        """Where finished captures for this VM end up."""
        base = self.completed_root
        return base / label if self.subdirs else base

    def vm_inflight_dir(self, label: str) -> Path:
        """Where tcpdump writes while the file is still open."""
        base = self.inflight_root
        return base / label if self.subdirs else base

    # ------------------------------------------------------------------
    # permissions
    # ------------------------------------------------------------------
    def resolve_drop_user(self) -> str:
        """Which account tcpdump drops to.

        RHEL/Oracle Linux package it as "tcpdump"; Debian/Ubuntu use "pcap".
        """
        if not self.drop_user_cfg or self.drop_user_cfg == "root":
            return "root"
        try:
            pwd.getpwnam(self.drop_user_cfg)
            return self.drop_user_cfg
        except KeyError:
            pass
        try:
            pwd.getpwnam("pcap")
            return "pcap"
        except KeyError:
            return ""

    def grant_capture_dir(self, directory: Path, user: str) -> None:
        """tcpdump drops privileges (-Z) BEFORE it creates its output file,
        so the capture directory must be writable by that user and not
        merely by root. This is the single most common reason captures fail
        with "Permission denied" while the directory plainly exists.

        Access is granted by POSIX ACL rather than chown: these directories
        are provisioned and ACL'd elsewhere, so taking ownership would fight
        whatever set them up and would quietly strip access other accounts
        depend on.
        """
        ctx = self.ctx
        ctx.run("mkdir", "-p", str(directory))
        if user in ("root", ""):
            return

        if not ctx.have("setfacl"):
            ctx.warn(f"setfacl not found -- cannot grant {user} write access to "
                     f"{directory}.")
            ctx.warn("Install it (dnf install acl), or tcpdump will fail the moment")
            ctx.warn("it drops privileges, with the directory looking perfectly fine.")
            return

        # -m MODIFIES the ACL: existing named users, the group entry and the
        # owner are all left alone. Never use --set here -- it replaces the
        # whole ACL, which is how you remove someone else's access without
        # ever seeing an error.
        #
        # rwx, not rw. On a directory 'x' is what permits entering it at all;
        # a directory granted rw without x cannot be written to.
        if not ctx.run("setfacl", "-m", f"u:{user}:rwx", str(directory)):
            ctx.warn(f"setfacl failed on {directory} -- captures will not be able "
                     "to write.")
            ctx.warn("Usually the filesystem is mounted without ACL support.")
            return

        # Default entry, so rotated files -- and any per-VM subdirectory made
        # later -- inherit the grant. Capital X means execute for directories
        # only: a new subdir stays traversable while the pcaps stay
        # non-executable.
        ctx.run("setfacl", "-d", "-m", f"u:{user}:rwX", str(directory))

        # Optional second grantee: whatever picks the captures up and moves
        # them on. This is how that process gets full read/write/delete
        # WITHOUT anyone having to own the files, and it is the reason this
        # script has no chown in it at all.
        if self.archive_reader:
            if not ctx.run("setfacl", "-m", f"u:{self.archive_reader}:rwx",
                           str(directory)):
                ctx.warn(f"Could not grant {self.archive_reader} access to "
                         f"{directory}.")
            ctx.run("setfacl", "-d", "-m", f"u:{self.archive_reader}:rwX",
                    str(directory))

    def grant_rundir(self, user: str) -> None:
        """RUNDIR holds pid files and the generated rotate hooks.

        The hook is executed by tcpdump AFTER -Z has dropped privileges, so
        the capture user has to traverse this directory and execute the hook
        in it. The mode is set explicitly rather than left to root's umask:
        on a hardened build with umask 077 the directory would come out
        0700, the hook would not be executable, and rotations would quietly
        stop moving files while tcpdump carried on capturing.
        """
        ctx = self.ctx
        ctx.run("mkdir", "-p", str(RUNDIR))
        ctx.run("chmod", "0750", str(RUNDIR))
        if user in ("root", "") or not ctx.have("setfacl"):
            return
        # rx, not rwx: the capture user runs the hook, it never writes here.
        ctx.run("setfacl", "-m", f"u:{user}:rx", str(RUNDIR))

    # ------------------------------------------------------------------
    def write_rotate_hook(self, sname: str, dest: Path, pattern: str) -> str:
        hook = RUNDIR / f"rotate-{sname}.sh"
        if self.ctx.dry_run:
            return str(hook)
        hook.write_text(ROTATE_HOOK.format(
            dest=dest, keep=self.archive_max, post=self.post,
            keep_original=self.keep_original, pattern=pattern,
        ), encoding="utf-8")
        # Owned by root and never written by the capture user, so read+execute
        # via ACL is enough and avoids making it world-executable.
        hook.chmod(0o750)
        if self.drop_user not in ("root", "") and self.ctx.have("setfacl"):
            if not self.ctx.q("setfacl", "-m", f"u:{self.drop_user}:rx",
                              str(hook)).ok:
                self.ctx.warn(f"Could not ACL {hook}; rotations may not move files.")
        return str(hook)

    # ------------------------------------------------------------------
    def check_disk(self) -> None:
        ctx = self.ctx
        if ctx.dry_run:
            return
        try:
            free_mb = shutil.disk_usage(self.directory).free // (1024 * 1024)
        except OSError:
            return
        if free_mb < self.min_free_mb:
            ctx.warn(f"Only {free_mb} MB free at {self.directory} "
                     f"(minimum {self.min_free_mb} MB).")
        else:
            ctx.log(f"Disk: {free_mb} MB free at {self.directory}.")

        # tcpdump holds the current file open for a whole rotation period.
        # On tmpfs that is RAM, and everything -- inflight/ and completed/
        # alike -- is lost on reboot, because both live under this one
        # path.
        fstype = ctx.qout("df", "-PT", self.directory)
        rows = fstype.splitlines() if fstype else []
        if len(rows) > 1 and len(rows[1].split()) > 1 \
                and rows[1].split()[1] == "tmpfs":
            ctx.warn(f"{self.directory} is tmpfs -- the open capture file is "
                     "held in RAM")
            ctx.warn(f"until it rotates, and is lost on reboot. With "
                     f"rotate_seconds={self.rotate} and snaplen={self.snaplen},")
            ctx.warn("size that against available memory or use disk-backed "
                     "storage.")

        # Verify the two directories really are one filesystem. If they are
        # not, the hook's mv is a copy-then-unlink and a collector can pick
        # up a half-written file -- the exact failure this layout exists to
        # prevent, and it would show up as nothing but occasional corrupt
        # pcaps.
        self._check_same_filesystem()

        if self.archive_max == "0":
            ctx.log("Retention: unlimited (pcap.archive_max_files: 0).")
            ctx.log(f"  {self.completed_name}/ grows until something else takes "
                    "the files away.")

    def _check_same_filesystem(self) -> None:
        ctx = self.ctx
        try:
            in_dev = self.inflight_root.stat().st_dev
            done_dev = self.completed_root.stat().st_dev
        except OSError:
            return
        if in_dev == done_dev:
            return
        ctx.warn(f"{self.inflight_name}/ and {self.completed_name}/ are on "
                 "DIFFERENT filesystems.")
        ctx.warn("Something has mounted one of them separately. The rotation "
                 "move is then a")
        ctx.warn("copy-then-unlink, not a rename, and a collector can read a "
                 "half-written")
        ctx.warn(f"pcap out of {self.completed_name}/. Unmount it, or point "
                 "pcap.directory at a")
        ctx.warn("path where both subdirectories live on one filesystem.")

    # ------------------------------------------------------------------
    def _report_ownership(self) -> None:
        """State the uid:gid the captures will be born with.

        -Z drops privileges BEFORE tcpdump creates its output file, so the
        pcap is owned by that account and its primary group and there is
        nothing to change afterwards. This script deliberately does no
        chown: the rotate hook inherits tcpdump's dropped privileges and
        has no CAP_CHOWN, so any attempt would fail silently on every
        rotation. Whatever needs access gets it by ACL (archive_reader).
        """
        ctx = self.ctx
        if self.drop_user in ("root", ""):
            ctx.log("Captures will be created as root (privilege drop "
                    "disabled).")
            return
        try:
            info = pwd.getpwnam(self.drop_user)
            ctx.log(f"Captures will be created as {self.drop_user} "
                    f"({info.pw_uid}:{info.pw_gid}).")
        except KeyError:
            pass
        if self.archive_reader:
            ctx.log(f"'{self.archive_reader}' is granted rwx on "
                    f"{self.directory} by ACL.")

    def _report_layout(self) -> None:
        """Print the contract the collector depends on."""
        ctx = self.ctx
        vm = "<vm>/" if self.subdirs else ""
        ctx.log(f"Capture layout under {self.directory}:")
        ctx.log(f"  {self.inflight_name}/{vm}   tcpdump's open file (still growing)")
        ctx.log(f"  {self.completed_name}/{vm}  closed files, safe to take")
        ctx.log("The move between them is a rename on one filesystem, so a")
        ctx.log(f"file under {self.completed_name}/ is never partial. Collect from")
        ctx.log(f"there and ignore {self.inflight_name}/ entirely.")

        if self.archive_max != "0":
            ctx.warn(f"pcap.archive_max_files is {self.archive_max}: files are "
                     f"deleted from {self.completed_name}/ once that many exist "
                     "per VM,")
            ctx.warn("whether or not anything has collected them. Set 0 unless "
                     "you have decided what you can lose.")

    def _check_post_process(self) -> None:
        """Post-processing needs wireshark-cli, and it runs as the capture
        user. Check now: a missing binary would otherwise show up only as a
        growing .postprocess-failed.log inside the archive."""
        ctx = self.ctx
        if self.post == "none":
            pass
        elif self.post == "dedupe":
            if not ctx.have("editcap"):
                ctx.warn("pcap.post_process is 'dedupe' but editcap is not "
                         "installed (dnf install wireshark-cli).")
        elif self.post == "no-retrans":
            if not ctx.have("tshark"):
                ctx.warn("pcap.post_process is 'no-retrans' but tshark is not "
                         "installed (dnf install wireshark-cli).")
            ctx.warn("post_process 'no-retrans' runs a two-pass tshark over every")
            ctx.warn("rotated file. That is CPU-heavy and grows with capture size --")
            ctx.warn(f"check it completes well inside rotate_seconds ({self.rotate}s)")
            ctx.warn("or hooks will overlap.")
        else:
            ctx.warn(f"pcap.post_process '{self.post}' is not recognised; expected "
                     "none|dedupe|no-retrans.")
            ctx.warn("No post-processing will be applied.")

        if self.post != "none" and self.keep_original != "true":
            ctx.warn("pcap.keep_original is false: post-processing will DELETE "
                     "packets with")
            ctx.warn("no preserved copy. For engagement captures this is usually the")
            ctx.warn("wrong call -- a filtered pcap cannot be un-filtered.")

    # ------------------------------------------------------------------
    def do_start(self) -> int:
        ctx = self.ctx
        if not self.enabled:
            raise Abort(
                "pcap.enabled is false in ovn-settings.yaml -- refusing to start.\n"
                "Set it to true, or this would capture without it being recorded "
                "in config."
            )
        ctx.require_cmd("tcpdump")

        if not ovn.br_exists(ctx, self.br_int) and not ctx.dry_run:
            raise Abort(f"{self.br_int} does not exist.")

        if not self.have_virsh:
            ctx.log("virsh not present -- resolving taps from OVS, naming by "
                    "inventory.")

        self.drop_user = self.resolve_drop_user()
        if not self.drop_user:
            ctx.warn(f"User '{self.drop_user_cfg}' does not exist -- running "
                     "tcpdump as root.")
            ctx.warn("That skips its privilege drop. Create the user, or set")
            ctx.warn("pcap.drop_user: root in the settings to make this explicit.")
            self.drop_user = "root"

        self.grant_capture_dir(Path(self.directory), self.drop_user)
        # Both roots explicitly: the default ACL entry on the parent only
        # applies to directories created after it was set, and these may
        # already exist from a previous run or from provisioning.
        self.grant_capture_dir(self.inflight_root, self.drop_user)
        self.grant_capture_dir(self.completed_root, self.drop_user)

        self._report_ownership()
        self._report_layout()
        self.grant_rundir(self.drop_user)
        self._check_post_process()
        self.check_disk()

        ctx.dr_head(f"Capture ports and mirrors on {self.br_int}")

        started = skipped = 0
        for vm in self.vms:
            result = self._start_one(vm)
            if result is True:
                started += 1
            elif result is False:
                skipped += 1

        if ctx.dry_run:
            return 0

        print("")
        if started == 0:
            ctx.warn(f"No captures started -- no VM in '{self.targets}' has a tap "
                     f"on {self.br_int}.")
            ctx.err(f"No captures started ({skipped} target(s) had no resolvable "
                    "tap).")
            ctx.err("Check that the VMs are running and their ports are bound:")
            ctx.err("  ovs-vsctl --columns=name,external_ids list Interface "
                    "| grep -A1 iface-id")
            ctx.err("  ovnctl pcap --status")
            return 1

        ctx.say(f"Capture ports are OVS ports on {self.br_int}, visible with:")
        ctx.say(f"  ovs-vsctl show          (Port {self.prefix}-*)")
        ctx.say("  ovs-vsctl list mirror   (the mirror objects)")
        ctx.say("They are deliberately absent from `ovnctl show`: no iface-id is")
        ctx.say("set, so OVN never sees them and will not try to bind them.")
        ctx.finish(f"{started} capture(s) started, {skipped} skipped -- "
                   f"{self.max_files} x {self.rotate}s per VM")
        return 0

    def _start_one(self, vm: VM) -> bool | None:
        """True started, False skipped, None already running."""
        ctx = self.ctx
        sname = safe_name(vm.name)
        mirport = f"{self.prefix}-{sname}"
        mirname = f"mirror-{sname}"
        label = self.label_for(vm)

        tap = self.tap_for(vm)
        if not tap:
            if ctx.dry_run:
                tap = f"<tap-for-{vm.name}>"
            else:
                # Always say why. This used to skip silently when virsh was
                # absent, producing an empty capture directory and no
                # explanation anywhere.
                ctx.warn(f"{vm.name} ({vm.ip}): {self.tap_absent_reason(vm)} "
                         "-- skipping.")
                return False

        # Stable capture interface -- name is independent of the tap.
        ctx.run("ovs-vsctl", "--may-exist", "add-port", self.br_int, mirport,
                "--", "set", "interface", mirport, "type=internal")
        ctx.run("ip", "link", "set", mirport, "up")

        # Replace any previous mirror for this VM.
        if ovn.mirror_exists(ctx, mirname):
            ctx.run("ovs-vsctl", "--", "--id=@m", "get", "mirror", mirname,
                    "--", "remove", "bridge", self.br_int, "mirrors", "@m")
            ctx.run("ovs-vsctl", "--if-exists", "destroy", "mirror", mirname)

        # Both directions of the VM's tap into the capture port.
        ctx.run("ovs-vsctl",
                "--", "--id=@src", "get", "port", tap,
                "--", "--id=@out", "get", "port", mirport,
                "--", "--id=@m", "create", "mirror", f"name={mirname}",
                "select-src-port=@src", "select-dst-port=@src",
                "output-port=@out",
                "--", "add", "bridge", self.br_int, "mirrors", "@m")

        outdir = self.vm_dir(label)
        indir = self.vm_inflight_dir(label)

        # Both per-VM directories need the capture user's ACL: tcpdump
        # creates in inflight/, and the rotate hook -- running with the
        # same dropped privileges -- unlinks from it and creates in
        # completed/.
        self.grant_capture_dir(indir, self.drop_user)
        self.grant_capture_dir(outdir, self.drop_user)

        # Filename: <prefix>_<vm-label>_<capture-interface>_<timestamp>
        #
        # The timestamp is a bare 14-digit YYYYMMDDHHMMSS -- no separators,
        # so the name sorts lexically in time order and `ls` alone gives
        # chronological sequence. tcpdump runs this through strftime when -G
        # rotates the file. Including the interface matters now that a VM can
        # be captured on more than one mirror port.
        fpattern = f"{self.file_prefix}_{label}_{mirport}_*.pcap*"
        outfile = (f"{indir}/{self.file_prefix}_{label}_{mirport}"
                   "_%Y%m%d%H%M%S.pcap")

        # Always. The hook is what moves a closed file into completed/,
        # which is the whole contract with the collector.
        hook = self.write_rotate_hook(sname, outdir, fpattern)

        pidfile = RUNDIR / f"{sname}.pid"
        if self._pid_alive(pidfile):
            ctx.log(f"  {vm.name}: capture already running "
                    f"(pid {pidfile.read_text().strip()}).")
            return None

        td = ["tcpdump", "-i", mirport, "-n", "-U",
              "-s", str(self.snaplen),
              "-G", str(self.rotate), "-W", str(self.max_files),
              "-Z", self.drop_user,
              "-w", outfile]
        # -z is the rotate hook. It runs on the CLOSED file, with tcpdump's
        # dropped privileges.
        td += ["-z", hook]
        if self.filter:
            td.append(self.filter)

        if ctx.dry_run:
            ctx.run(*td)
            return None

        return self._spawn(vm, td, pidfile, sname, tap, mirport, indir,
                           outdir, label)

    def _spawn(self, vm: VM, td: list[str], pidfile: Path, sname: str,
               tap: str, mirport: str, indir: Path, outdir: Path,
               label: str) -> bool:
        ctx = self.ctx
        errfile = RUNDIR / f"{sname}.err"
        try:
            with open(errfile, "wb") as errfh:
                proc = subprocess.Popen(
                    td, stdout=subprocess.DEVNULL, stderr=errfh,
                    start_new_session=True,
                )
        except OSError as exc:
            ctx.warn(f"{vm.name}: could not start tcpdump: {exc}")
            return False

        pidfile.write_text(f"{proc.pid}\n", encoding="utf-8")
        time.sleep(0.3)
        if proc.poll() is not None:
            ctx.warn(f"{vm.name}: tcpdump failed to start. See {errfile}")
            try:
                head = errfile.read_text(errors="replace").splitlines()[:3]
                ctx.note_stderr("\n".join(head))
            except OSError:
                pass
            return False

        if label != vm.name:
            ctx.log(f"  {vm.name} ({vm.ip}) [libvirt: {label}]: tap {tap} -> "
                    f"{mirport} -> {indir}/ -> {outdir}/")
        else:
            ctx.log(f"  {vm.name} ({vm.ip}): tap {tap} -> {mirport} -> "
                    f"{indir}/ -> {outdir}/")
        return True

    # ------------------------------------------------------------------
    @staticmethod
    def _pid_alive(pidfile: Path) -> bool:
        try:
            pid = int(pidfile.read_text().strip())
        except (OSError, ValueError):
            return False
        try:
            os.kill(pid, 0)
            return True
        except OSError:
            return False

    def do_stop(self) -> int:
        ctx = self.ctx
        ctx.dr_head("Stop captures and remove mirrors")
        stopped = 0

        for vm in self.vms:
            sname = safe_name(vm.name)
            mirport = f"{self.prefix}-{sname}"
            mirname = f"mirror-{sname}"
            pidfile = RUNDIR / f"{sname}.pid"

            if pidfile.exists():
                if self._pid_alive(pidfile):
                    pid = pidfile.read_text().strip()
                    if ctx.dry_run:
                        ctx.run("kill", pid)
                    else:
                        try:
                            os.kill(int(pid), signal.SIGTERM)
                            ctx.changes += 1
                            stopped += 1
                            ctx.log(f"  stopped capture for {vm.name} (pid {pid}).")
                        except (OSError, ValueError):
                            pass
                ctx.run("rm", "-f", str(pidfile))
            ctx.run("rm", "-f", str(RUNDIR / f"rotate-{sname}.sh"))

            if ovn.mirror_exists(ctx, mirname):
                ctx.run("ovs-vsctl", "--", "--id=@m", "get", "mirror", mirname,
                        "--", "remove", "bridge", self.br_int, "mirrors", "@m")
                ctx.run("ovs-vsctl", "--if-exists", "destroy", "mirror", mirname)
                ctx.log(f"  removed mirror {mirname}.")

            if mirport in ovn.list_ports(ctx, self.br_int):
                ctx.run("ovs-vsctl", "--if-exists", "del-port", self.br_int,
                        mirport)
                ctx.log(f"  removed capture port {mirport}.")

        if ctx.dry_run:
            return 0

        # The file tcpdump had OPEN never rotated, so its hook never ran and
        # it is sitting in inflight/. Move it across before anything else
        # touches the directory -- otherwise the most recent capture of
        # every VM is stranded somewhere the collector is told to ignore,
        # and that is the one most likely to matter.
        swept = 0
        for vm in self.vms:
            label = self.label_for(vm)
            swept += self.sweep_inflight(self.vm_inflight_dir(label),
                                         self.vm_dir(label))

        ctx.log(f"Stopped {stopped} capture(s), swept {swept} unrotated file(s) "
                f"into {self.completed_name}/.")
        if swept and self.post != "none":
            ctx.warn(f"Those {swept} file(s) were not post-processed: the hook "
                     "only ever runs on a rotation, and these never rotated.")
        return 0

    def sweep_inflight(self, indir: Path, dest: Path) -> int:
        """Move whatever is left in inflight/ into completed/.

        Same filesystem, so Path.replace is a rename and the file appears
        in completed/ complete or not at all -- the same guarantee the
        rotate hook gives.
        """
        ctx = self.ctx
        if not indir.is_dir() or indir == dest:
            return 0
        moved = 0
        for f in sorted(indir.glob("*.pcap")):
            try:
                dest.mkdir(parents=True, exist_ok=True)
                f.replace(dest / f.name)
                ctx.log(f"  swept {f.name} -> {dest}/")
                moved += 1
            except OSError as exc:
                ctx.warn(f"  could not move {f} to {dest} ({exc}) -- left in "
                         "place.")
        return moved

    # ------------------------------------------------------------------
    def do_status(self) -> int:
        ctx = self.ctx
        print("")
        print("=== Capture status ===")
        print(f"enabled: {self.enabled}   targets: {self.targets}")
        print(f"directory: {self.directory}   "
              f"({self.inflight_name}/ -> {self.completed_name}/)")
        if self.have_virsh:
            print(f"libvirt: available   bridge: {self.br_int}")
        else:
            print("libvirt: not installed -- taps resolved from OVS, names from "
                  "the inventory")
        print(f"rotation: {self.max_files} files x {self.rotate}s   "
              f"snaplen: {self.snaplen}   filter: {self.filter or '<none>'}")
        print("")
        print(f"{'VM':<10} {'LIBVIRT':<14} {'TAP':<10} {'CAPTURE PORT':<13} "
              f"{'MIRROR':<6} {'PID':<6} {'OPEN':<5} {'DONE':<6} COMPLETED DIR")

        for vm in self.vms:
            label = self.label_for(vm)
            sname = safe_name(vm.name)
            mirport = f"{self.prefix}-{sname}"
            pidfile = RUNDIR / f"{sname}.pid"
            state = pidfile.read_text().strip() if self._pid_alive(pidfile) else "-"
            mirror = "active" if ovn.mirror_exists(ctx, f"mirror-{sname}") else "-"
            tap = self.tap_for(vm) or "-"
            vdir = self.vm_dir(label)
            idir = self.vm_inflight_dir(label)
            pattern = f"{self.file_prefix}_{label}_*.pcap*"
            done = len(list(vdir.glob(pattern))) if vdir.is_dir() else 0
            open_n = len(list(idir.glob(pattern))) if idir.is_dir() else 0
            print(f"{vm.name:<10} {label:<14} {tap:<10} {mirport:<13} "
                  f"{mirror:<6} {state:<6} {open_n:<5} {done:<6} {vdir}")

        print("")
        base = Path(self.directory)
        if not base.is_dir():
            print(f"{self.directory} does not exist yet.")
            print("")
            return 0

        total = ctx.qout("du", "-sh", self.directory).split()
        free = ctx.qout("df", "-Ph", self.directory).splitlines()
        free_col = free[1].split()[3] if len(free) > 1 else "?"
        print(f"Total: {total[0] if total else '?'}   free: {free_col}")
        print("")
        print(f"Most recent COMPLETED capture per VM "
              f"(files in {self.inflight_name}/ are still being written):")
        for vm in self.vms:
            label = self.label_for(vm)
            vdir = self.vm_dir(label)
            candidates = sorted(vdir.glob(f"{self.file_prefix}_{label}_*.pcap*"),
                                key=lambda p: p.stat().st_mtime, reverse=True) \
                if vdir.is_dir() else []
            if candidates:
                latest = candidates[0]
                size = latest.stat().st_size
                print(f"  {vm.name:<10} {latest}  ({_human(size)})")
            else:
                print(f"  {vm.name:<10} (no captures yet)")
        print("")
        return 0


def _human(size: int) -> str:
    for unit in ("B", "K", "M", "G", "T"):
        if size < 1024:
            return f"{size:.0f}{unit}"
        size /= 1024.0
    return f"{size:.0f}P"


def main(ctx: Ctx, args: argparse.Namespace) -> int:
    ctx.load_config("ovn-pcap")
    ctx.require_cfg(*REQUIRED_CFG)

    ctx.require_root()
    ctx.require_cmd("ovs-vsctl")

    cmd = Pcap(ctx)
    cmd.build_virsh_map()

    if getattr(args, "list_steps", False):
        print("`ovnctl pcap` has modes rather than steps:")
        print("  --start    create mirrors and begin capturing")
        print("  --stop     stop tcpdump, remove mirrors and capture ports")
        print("  --restart  stop then start (re-resolves taps after a VM reboot)")
        print("  --status   show what is running (default)")
        return 0

    if args.start:
        return cmd.do_start()
    if args.stop:
        return cmd.do_stop()
    if args.restart:
        rc = cmd.do_stop()
        return cmd.do_start() or rc
    return cmd.do_status()